name: Build Image and Upload Artifact

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]  # 可选：当打标签时触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 仅当推送到 GHCR 时需要

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}        

    - name: Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          docker.io/${{ secrets.DOCKERHUB_REPO_NAME }}/comfyui:v0.3.26
          docker.io/${{ secrets.DOCKERHUB_REPO_NAME }}/comfyui:${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/comfyui:v0.3.26
          ghcr.io/${{ github.repository_owner }}/comfyui:${{ github.sha }}

    # - name: Build Docker Image
    #   run: |
    #     docker image build --file './Dockerfile' --tag 'comfyui:v0.3.26' --label 'any-intelligence=comfyui' './'          

    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: build-output
    #     path: |
    #       path/to/compiled/files/
    #       another/path/file.exe
    #     retention-days: 5  # 可选，设置保留天数（默认 90）